MODEL:
  PRETRAIN_PATH: '/home/eshan/.torch/models/resnet50-19c8e357.pth'


INPUT:
  SIZE_TRAIN: [128, 128]  # SIZE_TRAIN: [256, 128]
  SIZE_TEST: [128, 128]   # SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('RAP') # NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax'
  NUM_WORKERS: 5

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 280

  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 40
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  WEIGHT: "/Results_paper/TRAIN/fullbody/softmax_triplet_fullbody_background_0.3/resnet50_model_280.pth"

OUTPUT_DIR: "RESULTS/test_fullbody_softmax_0.3"  # OUTPUT_DIR: "/home/haoluo/log/reid/market1501/softmax_bs64_256x128"



